### ISSUE TITLE
Pie Legend bytes to MiB

### ISSUE THREAD

**Issue by Michsh** [grafana/piechart-panel#54] opened 2016-11-24 14:25 UTC
Pie legend dosen`t convert from bytes to MiB. Mouseover Pie convertion works.

![pielegend](https://cloud.githubusercontent.com/assets/8654261/20601656/6467c350-b262-11e6-8aeb-ae8a08721f9f.png)

**Comment by xiaoxue999** [comment] 2016-12-14 07:18
+1 all of Unit can not be change....

**Comment by fredprod** [comment] 2016-12-28 17:08
+1

**Comment by conet** [comment] 2017-03-06 09:33
This is a duplicate of issue #51, fixed by PR #66.

**Closed** 2017-04-19 17:24 UTC
