### ISSUE TITLE
Version 1.2.0 broke the pie charts and scroll bar

### ISSUE THREAD

**Issue by SaraFarsi** [grafana/piechart-panel#124] opened 2018-02-22 22:13 UTC
I updated Pie Chart from 1.6.0 to 1.2.0 and now my pie charts are so small that I can't see them clearly in Grafana and the scroll bar for the pie chart is gone. 
Thanks 
Sara

**Comment by marefr** [comment] 2018-02-23 08:54
Closing this as duplicate of #125

**Closed by marefr** 2018-02-23 08:54 UTC
