### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by karma1911** [grafana/piechart-panel#22] opened 2016-02-29 11:43 UTC
Hi there,

As far as I know, it seems we can't change the colors of the pie chart, as we can do in any other graphs. Any way to add this feature ?

**Comment by dotromain** [comment] 2016-03-13 08:15
+1

**Comment by jbonet** [comment] 2016-03-16 19:00
+1 here

**Comment by ronnykwon** [comment] 2016-03-17 18:50
+1

**Comment by digrich** [comment] 2016-04-02 22:48
+1

**Comment by bergquist** [comment] 2016-04-19 15:15
Closing this since its a dupe of https://github.com/grafana/piechart-panel/issues/18

**Closed by bergquist** 2016-04-19 15:15 UTC
Labels: enhancement

**Comment by xlash** [comment] 2016-04-19 15:25
+1

**Comment by lucas-matt** [comment] 2016-05-11 09:55
+1
